#!/bin/bash
# phpMan One-Line Installer
# =============================================================================
# Usage:
#   curl -sSL https://raw.githubusercontent.com/chedong/phpman/master/install.sh | bash
#   curl ... | bash -s -- --update
#   curl ... | bash -s -- --reindex
#   curl ... | bash -s -- --webroot /var/www/html
#   curl ... | bash -s -- --webroot /var/www/html --no-server
#   PHPMAN_PORT=9090 curl ... | bash
# =============================================================================
set -e

INSTALL_DIR="$HOME/.phpman"
REPO_URL="https://github.com/chedong/phpman.git"
PORT="${PHPMAN_PORT:-45678}"
WEBROOT=""
NO_SERVER=false

RED='\033[0;31m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'
YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

banner() {
    echo -e "${GREEN}"
    echo '  ____  _          __  ___'
    echo ' |  _ \| |__  _ __|  \/  | __ _ _ __'
    echo ' | |_) | '"'"'_ \| '"'"'_ \ |\/| |/ _` | '"'"'_ \'
    echo ' |  __/| | | | |_) | |  | | (_| | | | |'
    echo ' |_|   |_| |_| .__/|_|  |_|\__,_|_| |_|'
    echo '             |_|   Unix Man Page Web Interface & MCP Server'
    echo -e "${NC}"
}

# ─── Dependency Checks ────────────────────────────────────────────────────────

check_php() {
    if ! command -v php &>/dev/null; then
        echo -e "${RED}✗ PHP not found.${NC}"
        echo ""
        case "$(uname -s)" in
            Darwin) echo "  Install: brew install php" ;;
            Linux)
                if   command -v apt   &>/dev/null; then echo "  Install: sudo apt update && sudo apt install php-cli php-sqlite3"
                elif command -v dnf   &>/dev/null; then echo "  Install: sudo dnf install php-cli php-sqlite3"
                elif command -v yum   &>/dev/null; then echo "  Install: sudo yum install php-cli php-sqlite3"
                elif command -v pacman &>/dev/null; then echo "  Install: sudo pacman -S php php-sqlite"
                else echo "  Please install PHP 7.2+ with SQLite3 and FTS5 support"
                fi ;;
        esac
        echo ""
        exit 1
    fi
    local ver; ver=$(php -r 'echo PHP_VERSION;')
    local major; major=$(php -r 'echo PHP_MAJOR_VERSION;')
    local minor; minor=$(php -r 'echo PHP_MINOR_VERSION;')

    if [ "$major" -lt 7 ] || { [ "$major" -eq 7 ] && [ "$minor" -lt 2 ]; }; then
        echo -e "${RED}✗ PHP $ver — need 7.2+ (for SQLite3 FTS5)${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓${NC} PHP ${ver}"
}

check_sqlite3() {
    if ! php -r 'exit(extension_loaded("sqlite3") ? 0 : 1);' 2>/dev/null; then
        echo -e "${RED}✗ SQLite3 extension missing.${NC}"
        case "$(uname -s)" in
            Linux) echo "  Install: sudo apt install php-sqlite3 (or php<version>-sqlite3)" ;;
        esac
        exit 1
    fi
    echo -e "${GREEN}✓${NC} SQLite3 extension"
}

check_fts5() {
    local fts; fts=$(php -r '
        try { $db = new SQLite3(":memory:");
              $r = $db->querySingle("SELECT 1 FROM pragma_compile_options WHERE compile_options LIKE \"ENABLE_FTS5\"");
              echo $r ? "yes" : "no"; }
        catch (Exception $e) { echo "error"; }' 2>/dev/null)
    case "$fts" in
        yes) echo -e "${GREEN}✓${NC} FTS5 support" ;;
        no)  echo -e "${RED}✗ SQLite compiled without FTS5. Reinstall PHP with FTS5-enabled SQLite.${NC}"; exit 1 ;;
        *)   echo -e "${YELLOW}⚠${NC} Could not verify FTS5 (non-fatal)" ;;
    esac
}

check_git() {
    if ! command -v git &>/dev/null; then
        echo -e "${RED}✗ git not found — required for install/update.${NC}"
        echo "  macOS: xcode-select --install"
        echo "  Linux: sudo apt install git"
        exit 1
    fi
    echo -e "${GREEN}✓${NC} git $(git --version | awk '{print $NF}')"
}

run_checks() {
    echo ""
    echo -e "${CYAN}── System Check ──${NC}"
    check_php
    check_sqlite3
    check_fts5
    check_git
    echo -e "${GREEN}── All checks passed ──${NC}"
    echo ""
}

# ─── Config Generator ─────────────────────────────────────────────────────────

generate_config() {
    local target_dir="${1:-$INSTALL_DIR}"
    local config_file="$target_dir/phpman.config.php"
    local for_webroot="${2:-false}"  # true = public-facing, generate MCP_API_KEY

    if [ -f "$config_file" ]; then
        echo "  phpman.config.php already exists, skipping."
        return
    fi

    local home; home=$(php -r 'echo getenv("HOME") ?: ($_SERVER["HOME"] ?? "");')
    local mcp_key_line="// define('MCP_API_KEY', '');"
    local mcp_key=""

    if [ "$for_webroot" = true ]; then
        # Generate a random 32-char hex key for public-facing deployments
        mcp_key=$(php -r 'echo bin2hex(random_bytes(16));')
        mcp_key_line="define('MCP_API_KEY', '${mcp_key}');"
    fi

    cat > "$config_file" <<CONFIGEOF
<?php
// phpMan site configuration — generated by install.sh
// https://github.com/chedong/phpman

// --- PHPMAN_HOME ---
// Base directory for cache DB, logs, backups.
define('PHPMAN_HOME', '__HOME__/.phpman');

// --- LLM (v3.0 TLDR, reserved) ---
// define('LLM_API_KEY', '');
// define('LLM_API_URL', '');
// define('LLM_MODEL', 'gpt-4o-mini');

// --- MCP Authentication (#97) ---
// Set a secret key to require X-API-Key header on all MCP requests.
${mcp_key_line}

// --- Debug ---
// define('PHPMAN_DEBUG', false);
CONFIGEOF
    sed -i '' "s|__HOME__|$home|g" "$config_file" 2>/dev/null || sed -i "s|__HOME__|$home|g" "$config_file"
    echo "  Generated: $config_file"
    if [ -n "$mcp_key" ]; then
        echo "  MCP_API_KEY: $mcp_key"
        echo "  → MCP clients must send: X-API-Key: $mcp_key"
    fi
}

# ─── Deploy to Webroot ────────────────────────────────────────────────────────

do_deploy_webroot() {
    local target="$1"

    if [ ! -d "$target" ]; then
        echo -e "${RED}✗ Webroot does not exist: $target${NC}"
        exit 1
    fi

    echo "→ Deploying phpMan to $target ..."

    # Copy the single-file app + CSS
    cp "$INSTALL_DIR/phpMan.php" "$target/"
    cp "$INSTALL_DIR/phpman.css" "$target/" 2>/dev/null || true
    chmod 644 "$target/phpMan.php" "$target/phpman.css" 2>/dev/null || true

    # Generate config if not present
    generate_config "$target" true

    # Ensure data directory exists (outside webroot is handled by PHPMAN_HOME config)
    mkdir -p "$HOME/.phpman/db" "$HOME/.phpman/logs" "$HOME/.phpman/backups"

    echo ""
    echo -e "${GREEN}✓ Deployed to $target${NC}"
    echo "  phpMan.php → $target/phpMan.php"
    [ -f "$target/phpman.css" ] && echo "  phpman.css  → $target/phpman.css"
    echo "  config      → $target/phpman.config.php"
    echo "  data dir    → $HOME/.phpman/"
    echo ""
    echo "  Next: configure your web server to serve PHP from $target"
}

# ─── Install ──────────────────────────────────────────────────────────────────

do_install() {
    banner
    run_checks

    mkdir -p "$INSTALL_DIR"

    if [ -d "$INSTALL_DIR/.git" ]; then
        echo -e "${YELLOW}phpMan already installed at $INSTALL_DIR${NC}"
        echo "Use --update to pull latest, or --reindex to rebuild index."
        echo ""
    else
        echo "→ Cloning phpMan into $INSTALL_DIR ..."
        git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
    fi

    cd "$INSTALL_DIR"

    echo "→ Building FTS5 search index (man + pydoc3 + ri) ..."
    echo "  (this may take 1–2 minutes on first run)"
    php phpMan.php --build-index

    generate_config "$INSTALL_DIR"

    echo ""
    echo -e "${GREEN}✓ phpMan installed!${NC}"

    # If --webroot specified, deploy there too
    if [ -n "$WEBROOT" ]; then
        do_deploy_webroot "$WEBROOT"
    fi

    if [ "$NO_SERVER" = false ]; then
        start_server
    fi
}

# ─── Update ───────────────────────────────────────────────────────────────────

do_update() {
    banner

    if [ ! -d "$INSTALL_DIR/.git" ]; then
        echo -e "${RED}Not installed. Run without --update first.${NC}"
        exit 1
    fi

    run_checks

    cd "$INSTALL_DIR"
    echo "→ Pulling latest code..."
    git pull --ff-only

    echo "→ Rebuilding FTS5 search index..."
    php phpMan.php --build-index

    if [ -n "$WEBROOT" ]; then
        do_deploy_webroot "$WEBROOT"
    fi

    echo ""
    echo -e "${GREEN}✓ phpMan updated!${NC}"

    if [ "$NO_SERVER" = false ]; then
        start_server
    fi
}

# ─── Reindex Only ─────────────────────────────────────────────────────────────

do_reindex() {
    if [ ! -f "$INSTALL_DIR/phpMan.php" ]; then
        echo -e "${RED}phpMan.php not found at $INSTALL_DIR — run install first.${NC}"
        exit 1
    fi

    echo "→ Rebuilding search index..."
    php "$INSTALL_DIR/phpMan.php" --build-index
    echo -e "${GREEN}✓ Index rebuilt.${NC}"
}

# ─── Start Server ─────────────────────────────────────────────────────────────

start_server() {
    echo ""
    echo "  ┌──────────────────────────────────────────────────────────┐"
    printf "  │  %-56s │\n" "${GREEN}phpMan ready${NC}"
    printf "  │  %-56s │\n" "${BLUE}→ http://localhost:${PORT}/phpMan.php${NC}"
    echo "  │                                                          │"
    printf "  │  %-56s │\n" "Man page:    /phpMan.php/man/ls"
    printf "  │  %-56s │\n" "Perldoc:     /phpMan.php/perldoc/File::Basename"
    printf "  │  %-56s │\n" "Python:      /phpMan.php/pydoc/os.path"
    printf "  │  %-56s │\n" "Ruby:        /phpMan.php/ri/String"
    printf "  │  %-56s │\n" "Search:      /phpMan.php/search/git"
    printf "  │  %-56s │\n" "MCP endpoint:/phpMan.php/mcp"
    echo "  │  ${YELLOW}Press Ctrl+C to stop${NC}                                   │"
    echo "  └──────────────────────────────────────────────────────────┘"
    echo ""

    cd "$INSTALL_DIR"
    php -S "localhost:${PORT}"
}

# ─── Main ────────────────────────────────────────────────────────────────────

# Parse arguments
while [ $# -gt 0 ]; do
    case "$1" in
        --update|-u)
            MODE="update"; shift ;;
        --reindex|-r)
            MODE="reindex"; shift ;;
        --webroot)
            WEBROOT="$2"; shift 2 ;;
        --webroot=*)
            WEBROOT="${1#*=}"; shift ;;
        --no-server)
            NO_SERVER=true; shift ;;
        --help|-h)
            echo "phpMan Installer"
            echo ""
            echo "Usage:"
            echo "  curl -sSL https://raw.githubusercontent.com/chedong/phpman/master/install.sh | bash"
            echo ""
            echo "With options (note the -s -- between bash and options):"
            echo "  curl ... | bash -s -- --update"
            echo "  curl ... | bash -s -- --webroot /var/www/html"
            echo "  curl ... | bash -s -- --webroot /var/www/html --no-server"
            echo "  curl ... | bash -s -- --reindex"
            echo ""
            echo "Options:"
            echo "  --update          Pull latest code + reindex + start server"
            echo "  --reindex         Rebuild FTS5 search index only"
            echo "  --webroot <path>  Also deploy phpMan.php + config to a webroot directory"
            echo "  --no-server       Skip starting php -S (use with --webroot for Apache/Nginx)"
            echo ""
            echo "Environment:"
            echo "  PHPMAN_PORT=9090   Override default port (45678)"
            exit 0
            ;;
        *)  shift ;;
    esac
done

case "${MODE:-install}" in
    install) do_install ;;
    update)  do_update ;;
    reindex) do_reindex ;;
esac
