#!/usr/bin/env php
<?php
/**
 * detect-tools.php — Check which documentation tools are available on this server.
 * Outputs PHP constant definitions for inclusion in phpman config.
 *
 * Called by Makefile during deploy. Output is redirected to a config include file.
 *
 * Usage:
 *   php cli/detect-tools.php > ~/.phpman/tools_config.php
 *
 * The generated file is @include'd by src/config.php.
 */

$tools = [
    'perldoc' => 'perldoc',
    'pydoc'   => 'pydoc3',
    'ri'      => 'ri',
    'info'    => 'info',
];

echo "<?php\n";
echo "// Auto-generated by cli/detect-tools.php — do not edit manually.\n";
echo "// Regenerate: php cli/detect-tools.php > ~/.phpman/tools_config.php\n";
echo "// Updated: " . gmdate('Y-m-d H:i:s') . " UTC\n\n";

foreach ($tools as $key => $bin) {
    $which = trim(shell_exec('which ' . escapeshellarg($bin) . ' 2>/dev/null') ?? '');
    $has = $which !== '' ? 'true' : 'false';
    echo "define('PHPMAN_HAS_" . strtoupper($key) . "', {$has}); // {$bin}" . ($has === 'true' ? " → {$which}" : " — not found") . "\n";
}
